---
title: "EDUC 641 Assignments"
site: distill::distill_website
output:
  html_document:
    css: educquant.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1. General Guidelines

The goal of the assignments is to practice the concepts and vocabulary we have been modeling in class and implement some of the techniques we have learned. You may work on your own or collaborate with one (1) partner. Please make sure that you engage in a a full, fair and mutually-agreeable collaboration if you do choose to collaborate. If you do collaborate, you should plan, execute and write-up your analyses together, not simply divide the work. Please make sure to indicate clearly when your work is joint and any other individual or resource (outside of class material) you consulted in your responses.

(Here we need to add more details about global expectations and requirements for all the assignments, grading and points distribution for participation, five assignments, and/or final project/exam, late submission policy, etc. from syllabus.)

### 2. Submission Requirements

Please upload below two files on Canvas before TBD time:  

 * An .html or .pdf file that includes both - 
   + your typed responses (in your own words and not identical to anybody else's), tables, and/or figures to the problems  
   + and the R code chunks that generated your answers (hint: if you choose to compose your answers in markdown, simply set up echo = TRUE, include = TRUE in you .Rmd file)  
   
 * The .Rmd or .R file that you used to render the tables and figures in the above html/pdf. 

### 3. Details about Assignments

#### 3.1. Assignment 1

Categorical data 1: data structure and descriptives 

Objectives of this assignment

 * Describe and summarize categorical data

 * Create visualizations of categorical data

Deadline: TBD

Download: [html file](./assignments/assignment01.html); [cat.csv dataset](./data/cat.csv)

Key: [doc file](./assignments/keys/assignment01_key.docx); [R script](./assignments/keys/assignment01_key.R)

#### 3.2. Assignment 2 

Categorical data 2: chi-square analysis

Objectives of this assignment

 * Describe relationships between categorical variables
 
 * Calculate an index of the strength of the relationship between two categorical variables, the chi-squared ($\chi^2$) statistic
 
 * Formulate and describe the purpose of a null hypothesis
 
 * Conceptually describe the criteria to make a statistical inference from a sample to a population
 
 * Interpret and report the results of a contingency-table analysis and a statistical inference from a chi-squared statistic

Deadline: TBD

Download: [html file](./assignments/assignment02.html); [cat.csv dataset](./data/cat.csv)

Key: [doc file](./assignments/keys/assignment02_key.docx); [R script](./assignments/keys/assignment02_key.R)

#### 3.3. Assignment 3 

Continuous data 1: summarizing and displaying continuous data

Objectives of this assignment

 * Describe and summarize continuous data

 * Create visualizations of continuous data

Deadline: TBD

Download: [html file](./assignments/assignment03.html); [cont.csv dataset](./data/cont.csv)

Key: [doc file](./assignments/keys/assignment03_key.docx); [R script](./assignments/keys/assignment03_key.R)

#### 3.4. Assignment 4 

Continuous data 2: intro to bivariate regression

Deadline: TBD

Download: [html file](./assignments/assignment04.html); [cont.csv dataset](./data/cont.csv)

Key: [doc file](./assignments/keys/assignment04_key.docx); [R script](./assignments/keys/assignment04_key.R)


#### 3.5. Assignment 5 

Final assignment 

Deadline: TBD

Download: [html file](./assignments/assignment05.html); [cont.csv dataset](./data/cont.csv)

Key: [doc file](./assignments/keys/assignment05_key.docx); [R script](./assignments/keys/assignment05_key.R)






