---
title: "EDUC 641 Schedule"
site: distill::distill_website
output:
  html_document:
    toc: TRUE
    toc_depth: 2
    toc_float: TRUE
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Note: readings are intended to be completed *after* subject is covered by class lecture; however, you are welcome to read them in advance. You are encouraged to preview the slides prior to that unit's lectures.**

*We have provided the lecture slides in .html and .pdf format. Some of the slide features will only work in .html format while connected to the internet. Feel free to download the PDFs for later use (you'll miss out on animations and interactivities, but most information will render correctly).*

## Unit 0

**Topic: Introduction to scientific principles and data analysis**

Objectives:

- Describe goals of course and principles of scientific research
- Describe types of and differences in measurement scales
- Install and familiarize self with statistical software

Readings: 

- Complete **prior to Sept. 29** class: [LSWR Chapters 2 and 3](https://learningstatisticswithr.com/lsr-0.6.pdf) and [Clayton 2020](https://nautil.us/how-eugenics-shaped-statistics-238014/)

Lectures:

- Class 1 (9/27) slides: [html](./slides/EDUC641_1_intro.html) | [pdf](./slides/EDUC641_1_intro.pdf)
- Class 2 (9/29) slides: [html](./slides/EDUC641_2_measures.html) | [pdf](./slides/EDUC641_2_measures.pdf)
- R Tutorial slides: [html](./slides/tutorial.html)
- Lab slides: [html](https://claireconglizhang.github.io/my-slides/EDUC64122F/lab1.html)

## Unit 1 

**Topic: Summarizing and displaying categorical data**

Objectives:

- Understand and implement principles of tabular data in R
- Describe and summarize quantitative data that are categorical
- Create visualizations of quantitative data that are categorical
- Write R scripts to conduct these analyses

Readings: 

- Complete **prior to Oct. 6** class: [LSWR Chapter 6](https://learningstatisticswithr.com/lsr-0.6.pdf) and [Evans 2020](https://www.newstatesman.com/uncategorized/2020/07/ra-fisher-and-science-hatred); alternate source for [Evans](./assignments/evans_2020.pdf)

Lectures: 

- Class 3 (10/4) slides: [html](./slides/EDUC641_3_categdescr.html) | [pdf](./slides/EDUC641_3_categdescr.pdf)
- Data: [deathpenalty.csv](./data/deathpenalty.csv) | [codebook](./data/deathpenalty_codebook.pdf)
- R code: [R script](./slides/EDUC641_3_code.R)
- Lab slides: [html](https://claireconglizhang.github.io/my-slides/EDUC64122F/lab2.html#1)

Assignment 1: 

- Due: October 10, 11:59pm
- [html file](./assignments/assignment01.html)
- [cat.csv dataset](./data/cat.csv)

## Unit 2

**Topic: Examining the relationship between categorical variables**

Objectives:

 * Describe relationships between quantitative data that are categorical
 * Calculate an index of the strength of the relationship between two categorical variables, the chi-squared ( $\chi^2$) statistic
 * Write R scripts to conduct these analyses
 * Formulate and describe the purpose of a null hypothesis
 * Conceptually describe the criteria to make a statistical inference from a sample to a population
 * Interpret and report the results of a contingency-table analysis and a statistical inference from a chi-squared statistic

Readings: 

- Complete **prior to Oct. 13** class: [LSWR Chapters 11 and 12](https://learningstatisticswithr.com/lsr-0.6.pdf) and [Levy 2019](http://gppreview.com/2019/12/16/eugenics-ethics-statistical-analysis/) 
   + See lecture notes on what to focus on (and not) in LSWR

Lectures:

- Classes 4-5 (10/6 and 10/11) slides: [html](./slides/EDUC641_4_categrel.html) | [pdf](./slides/EDUC641_4_categrel.pdf)
- Class 6 (10/13) slides: [html](./slides/EDUC641_6_history.html) | [pdf](./slides/EDUC641_6_history.pdf)


- Data: [deathpenalty.csv](./data/deathpenalty.csv) | [codebook](./data/deathpenalty.csv) 
- R code: [R script](./slides/EDUC641_4_code.R)
 
Assignment 2: 

- Due: October 19, 11:59pm
- [html file](./assignments/assignment02.html)
- [cat.csv dataset](./data/cat.csv)

## Unit 3

**Topic: Summarizing and displaying continuous data**

Objectives:

- Describe and summarize quantitative data that are continuous
- Describe the purpose and compute the following measures of central tendency: mean, median and mode
- Descripe the purpose and compute the following measures of variability: quartiles, inter-quartile range, range, variance and standard deviation
  + Describe conceptually the principles of skewness and kurtosis
- Create visualizations of quantitative data that are continuous using R
  + Includes constructing histograms, densities, stem-and-leaf, and box-and-whisker plots
- Construct a standardized or $z$-score and explain its substantive meaning
- Use a $z$-transformation to compare distributions, observations within distributions and interpret outlying values
- Describe special features of a normal (and standard normal) distribution
- Interpret a $z$-statistic table
- Describe the distribution of repeated sample statistics drawn from a population, how this relates to the Central Limit Theorem (CLT) and how this is informative to statistical hypothesis testing
- Determine whether the mean value of a sample is different than a defined population mean, both when the population standard deviation of the variable is known ( $z$-test) and when it is unknown (one-sample $t$-test)

Readings: 

- Complete **prior to Oct. 27** class: [LSWR Chapter 5](https://learningstatisticswithr.com/lsr-0.6.pdf) and [Hu 2021](https://bostonreview.net/science-nature-race/lily-hu-race-policing-and-limits-social-science)
- Complete **prior to Nov. 10** class: [LSWR Chapter 10](https://learningstatisticswithr.com/lsr-0.6.pdf)


Lecture slides: 

- Classes 7-8 (10/18 & 10/20) slides: [html](./slides/EDUC641_7_continuousdescr.html) | [pdf](./slides/EDUC641_7_continuousdescr.pdf)
- Class 9 (10/25) slides: [html](./slides/EDUC641_9_transformations.html) | [pdf](./slides/EDUC641_9_transformations.pdf)
- Classes 10-12 (10/27, 11/1, & 11/3) slides: [html](./slides/EDUC641_10_inference.html) | [pdf](./slides/EDUC641_10_inference.pdf)

- Data: [life_expectancy.csv](./data/life_expectancy.csv) | [codebook](./data/life_expectancy_codebook.pdf)
- R code: [R Script](./slides/EDUC641_7_code.R)

Assignment 3: 

- Due: November 9, 9:00am
- [html file](./assignments/assignment03.html)
- [cont.csv dataset](./data/cont.csv)


## Unit 4

**Topic: Describing relationships between continuous data**

Objectives:

- Describe relationships between quantitative data that are continuous
- Visualize and substantively describe the relationship between two continuous variables
- Describe and interpret a fitted bivariate regression line
- Describe and interpret components of a fitted bivariate linear regression model
- Visualize and substantively interpret residuals resulting from a bivariate regression model
- Conduct a statistical inference test of the slope and intercept of a bivariate regression model
- Write R scripts to conduct these analyses
- Articulate modern critiques of null-hypothesis significance testing framework
- Describe strategies to improve replicability and generalizability of quantitative research

Readings: 

- Complete **prior to Nov. 22** class: [LSWR Chapter 15.1 and 15.2](https://learningstatisticswithr.com/lsr-0.6.pdf)

Lecture slides: 

- Class 13 (11/8) slides: [html](./slides/EDUC641_14_continuousrel.html) | [pdf](./slides/EDUC641_14_continuousrel.pdf)
- Class 14 (11/10) slides: [html](./slides/EDUC641_15_regression.html) | [pdf](./slides/EDUC641_15_regression.pdf)
- Class 15-16 slides (11/15 & 11/22): [html](./slides/EDUC641_16_residuals.html) | [pdf](./slides/EDUC641_16_residuals.pdf)
  + **No class on 11/17 (David traveling for conference) and 11/24 (university holiday)**

- Data:  [life_expectancy.csv](./data/life_expectancy.csv)
- R code: [R script](./slides/EDUC641_14_code.R)

Assignment 4: 

- Due Nov. 28, 11:59pm
 - [html file](./assignments/assignment04.html)
 - [cont.csv](./data/cont.csv)

## Unit 5

- Classes 17-18 (11/29 & 12/1): 
<!-- [html](./slides/EDUC641_17_critiques.html) | [pdf](./slides/EDUC641_17_critiques.pdf) -->

- Data management cheat sheet: [pdf]

## Final Assignment

 * Due December 7 at 11:59pm
<!-- - [html file](./assignments/assignment05.html) -->
<!-- - [ah01.csv](./data/ah01.csv); [ah02.csv](./data/ah02.csv) -->

