---
title: "EDUC 641 R Basics"
author: "Instruction Team"
date: "Last update: 2021 Summer"
output:
  xaringan::moon_reader:
    css: [default, uo, nhsr-fonts]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
name: toc
<style type="text/css">
.remark-slide-content {
    font-family: font-family: 'Alegreya Sans', sans-serif;
    font-size: 24px;
    padding: 1em 2em 1em 2em;
}
</style>

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Table of Contents

1. [R and RStudio](#ide) 

2. [Git and Github](#git)

3. [R Script and RMD](#script)

4. [R project Workflow](#workflow)

5. [Resources](#resources)

---
# Notes

 * Each of the first four units ([R](#ide), [Git](#git), [R script](#script), and [workflow](#workflow)) has three ordered components, terminologies, instructions, and a GIF demonstration of the instructions
 
 * A disclaimer. There're unlimited online resources for you to learn R. Many things you learn from this slides deck can probably be done in different way(s). 
 
 * Our goal is, for those of you who had no previous experience with R, to provide you some simple and clear guidance so you'll be able to start using R and avoid taking on unnecessary long road to get ready for the [EDUC 641](https://uo-educ-quant.github.io/641/) classes.
 
 * To learn more about R, check out the [Resources](#resources) section (and consider enrolling in some R programming courses)
 
 * This slide deck is built using the xaringan package with the UO theme (with slightly customized css)
 
---
class: inverse, center, middle
name: ide
# 1. R and RStudio
(Back to [the Table of Content](#toc))
---
# Terminologies

 * [R](https://www.r-project.org/) ([wiki](https://en.wikipedia.org/wiki/R_(programming_language)) is a free and open-source programming language, created by Ross Ihaka and Robert Gentleman at the University of Auckland, New Zealand.
 
 * [RStudio](https://www.rstudio.com/products/rstudio/#rstudio-desktop) is an integrated development environment (IDE) for R and provides a graphical interface to R 
  + It includes a console, a syntax-highlighting editor that supports direct code execution and tools for plotting, history, debugging and workspace management.
  + It has two versions: RStudio desktop (the software we'll be using) that allows you to run RStudio on your desktop and RStudio server that allows you to access RStudio via a web browser

---
# Instructions

1. Download [R](https://www.r-project.org/)

2. Download [RStudio](https://www.rstudio.com/products/rstudio/download/preview/)

3. 
---
# Demonstration


---
class: inverse, center, middle
name: git
# 2. Git and GitHub
(Back to [the Table of Content](#toc))
---
# Terminologies

---
# Instructions

---
# Demonstration

---
class: inverse, center, middle
name: script
# 3. R Script and RMD
(Back to [the Table of Content](#toc))
---
# Terminologies

---
# Instructions

---
# Demonstration


---
class: inverse, center, middle
name: workflow
# 4. R Project Workflow
(Back to [the Table of Content](#toc))
---
# Terminologies

---
# Instructions

---
# Demonstration


---
class: inverse, center, middle
name: resources
# 5. Resources
(Back to [the Table of Content](#toc))
---
# Resources for this slides deck

---
# Important Resources


---
# Runners up














