---
title: "EDUC 641 Assignment 4"
subtitle: "(Correlation and t-test)"
output: html_document
---
```{R, setup, include = FALSE}
if (!require(pacman)) install.packages('pacman', repos = 'https://cran.rstudio.com')
pacman::p_load(here, tidyverse, ggplot2, xaringan, knitr, kableExtra)

opts_chunk$set(include = FALSE)
```

### General Guidelines

* The purpose of this assignment is to practice the concepts and vocabulary we have been modeling in class and implement some of the techniques we have learned. You may work on your own or collaborate with one partner. Please make sure that you engage in a a full, fair and mutually-agreeable collaboration if you do choose to collaborate. If you do collaborate, you should plan, execute and write-up your analyses together, not simply divide the work. Please make sure to indicate clearly when your work is joint and any other individual or resource (outside of class material) you consulted in your responses.

### Submission Requirements

Please upload below two files on Canvas before TBD time:  

 * An .html or .pdf file that includes both - 
   + your typed responses (in your own words and not identical to anybody else's), tables, and/or figures to the problems  
   + and the R code chunks that generated your answers (hint: if you choose to compose your answers in markdown, simply set up echo = TRUE, include = TRUE in you .Rmd file)  
   
 * The .Rmd or .R file that you used to render the tables and figures in the above html/pdf. 

### Objectives of this assignment

 * 

 * 

### Data Background

The dataset we'll be using in this assignment is drawn from the NCRECE [Teacher Professional Development Study (PDS)](https://www.icpsr.umich.edu/web/ICPSR/studies/34848) data. This professional development study was a randomized controlled evaluation of two forms of professional development (PD) - coursework (phase 1) and consultancy (phase 2) - delivered to about 490 early childhood education teachers across the nation. These PD supports aimed to improve teachers' implementation of language/literacy activities and interactions with children, as well as promote gains in children's social and academic development. 

The primary goal of the intervention was to improve language and literacy skills, however, prior studies have shown that there were no observed average impacts of either the coursework or the consultancy PD intervention on student outcomes at the end of phase 2 ([Pianta et al., 2017](https://www.tandfonline.com/doi/abs/10.1080/10409289.2017.1319783?journalCode=heed20)). We draw a sample similar to the one used in Pianta et al (2017) but limit to only teachers who were treated in phase 1 then assigned to either treatment or control group in phase 2. This sample allows you to answer two questions: (a) did the consultancy PD intervention improve student vocabulary? and (b) did the dosage of the coursework PD intervention impact student vocabulary skills? You will answer these two questions in the paired assignments 3 and 4.

**Sample**. Our dataset is teacher-level data for 126 preschool teachers. They were in the treatment group for the 14-session coursework PD intervention, had no missing data on coursework attendance, and were in either the treatment or control group for the consultancy PD intervention.

**Key variables**. We have two treatment measures, a binary variable indicating whether the teacher was treated in the consultancy PD intervention and an integer variable capturing the total number of sessions the teacher participated in the coursework PD intervention. We also have an outcome measure, the teacher's average student standard score on a receptive vocabulary test (Peabody Picture Vocabulary Test-3rd edition). 

Details on all variables are as follows:

 * *tchid*, the teacher's unique identification number.
 * *treat*, consultancy treatment indicator, coded 1 if the teacher was in the treatment group, coded 0 if the teacher was in the control group.  
 * *coursework*, measure of how many sessions the teacher had participated in the coursework. 
 * *vocabulary*, the teacher's average student score on receptive vocabulary test. 

### Assignment Details

Prepare your data: open your RStudio, create a project and save it. Go to the root directory of the project and create a folder named "data". Download the [cont2.csv dataset, NOT the one used in assignment 3](./data/cont.csv) and store it in the folder "data". Create an Rmd/R file in the project root directory. Then read the data into your R environment. Make sure to check whether the variable *treat* is factor as well as whether *coursework* and *vocabulary* are double. Transform them into correct types if needed. 

#### 1. Descriptive Statistics

1.1. Summarize the cont2.csv dataset (leave out *tchid*). Specifically, create a table to show the mean and standard deviation of each continuous variable and the count and percentage for each category of the categorical variables. Write 2-3 sentences to report and interpret these statistics.

1.2. Summarize the variable *vocabulary* by *treat*. Specifically, create a table to show the mean and standard deviation of *vocabulary* for the treatment and control groups separately. Also, create a boxplot (make sure to label the x- and y-axes) to visualize the distributions of *vocabulary* for the treatment and control groups separately. You may choose one of the two ways: (a) use base R code to produce two plots side-by-side, or (b) use {ggplot2} package to produce one plot.

 * 1.2.1. Write 2-3 sentences to report and interpret these statistics. 
 * 1.2.2. Compare the observed mean of *vocabulary* for the treatment group and control group. Can you decide whether the treated students score higher or lower than their peers in the studied population? Why or why not?

1.3. Create a plot (make sure to label the x- and y- axes) to visualize the relationship between *vocabulary* and *coursework*. 

 * 1.3.1. Write one sentence to describe your observations. 
 * 1.3.2. Can you conclude whether teachers who attended more coursework have higher student score? Why or why not?

#### 2. Research Question (a): Did the consultancy PD intervention improve student vocabulary?

2.1. Write your null hypothesis and the assumption(s) you make in investigating this research question.

2.2. Test your hypothesis

 * 2.2.1. What hypothesis testing you choose to answer this question? Why?

 * 2.2.2. Run the test then report your results.

2.3. Write a short paragraph to answer this research question.

#### 3. Research Question (b): Did the dosage of the coursework PD intervention impact student vocabulary skills?

3.1. Write your null hypothesis and the assumption(s) you make in investigating this research question.

3.2. Test your hypothesis

 * 3.2.1. Which hypothesis testing you choose to answer this question? Why?

 * 3.2.2. Run the test then report your results.

3.3. Write a short paragraph to answer this research question.

